# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\projects\youdao-word-reformat\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.begin = QtWidgets.QPushButton(self.centralwidget)
        self.begin.setGeometry(QtCore.QRect(470, 180, 211, 91))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(28)
        self.begin.setFont(font)
        self.begin.setObjectName("begin")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(660, 10, 21, 21))
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.mini = QtWidgets.QPushButton(self.centralwidget)
        self.mini.setGeometry(QtCore.QRect(630, 10, 21, 21))
        self.mini.setText("")
        self.mini.setObjectName("mini")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(20, 70, 421, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(20, 130, 421, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.output.setFont(font)
        self.output.setObjectName("output")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 181, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 141, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(470, 60, 111, 71))
        self.groupBox.setObjectName("groupBox")
        self.word = QtWidgets.QRadioButton(self.groupBox)
        self.word.setEnabled(True)
        self.word.setGeometry(QtCore.QRect(10, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.word.setFont(font)
        self.word.setToolTipDuration(3)
        self.word.setObjectName("word")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.word, 3)
        self.txt = QtWidgets.QRadioButton(self.groupBox)
        self.txt.setGeometry(QtCore.QRect(10, 40, 89, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.txt.setFont(font)
        self.txt.setToolTipDuration(4)
        self.txt.setObjectName("txt")
        self.buttonGroup_2.addButton(self.txt, 4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 421, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.format1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.format1.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.format1.setFont(font)
        self.format1.setToolTipDuration(1)
        self.format1.setObjectName("format1")
        self.select_format = QtWidgets.QButtonGroup(MainWindow)
        self.select_format.setObjectName("select_format")
        self.select_format.addButton(self.format1, 1)
        self.format2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.format2.setGeometry(QtCore.QRect(10, 70, 51, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.format2.setFont(font)
        self.format2.setToolTipDuration(2)
        self.format2.setObjectName("format2")
        self.select_format.addButton(self.format2, 2)
        self.sample_show = QtWidgets.QLabel(self.groupBox_2)
        self.sample_show.setGeometry(QtCore.QRect(80, 10, 331, 121))
        self.sample_show.setText("")
        self.sample_show.setPixmap(QtGui.QPixmap(":/images/sample.png"))
        self.sample_show.setObjectName("sample_show")
        self.icon_label = QtWidgets.QLabel(self.centralwidget)
        self.icon_label.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap(":/images/icon.png"))
        self.icon_label.setObjectName("icon_label")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(50, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.input_select = QtWidgets.QPushButton(self.centralwidget)
        self.input_select.setGeometry(QtCore.QRect(390, 80, 41, 21))
        self.input_select.setObjectName("input_select")
        self.output_select = QtWidgets.QPushButton(self.centralwidget)
        self.output_select.setGeometry(QtCore.QRect(390, 140, 41, 21))
        self.output_select.setObjectName("output_select")
        self.link_txwh = QtWidgets.QPushButton(self.centralwidget)
        self.link_txwh.setGeometry(QtCore.QRect(480, 280, 75, 23))
        self.link_txwh.setObjectName("link_txwh")
        self.link_github = QtWidgets.QPushButton(self.centralwidget)
        self.link_github.setGeometry(QtCore.QRect(580, 280, 75, 23))
        self.link_github.setObjectName("link_github")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.begin.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "从有道单词导出的单词文件目录："))
        self.label_2.setText(_translate("MainWindow", "存放格式化后的文件目录："))
        self.groupBox.setTitle(_translate("MainWindow", "输出格式"))
        self.word.setText(_translate("MainWindow", "Word"))
        self.txt.setText(_translate("MainWindow", "TXT"))
        self.groupBox_2.setTitle(_translate("MainWindow", "选择排版"))
        self.format1.setText(_translate("MainWindow", "排版1"))
        self.format2.setText(_translate("MainWindow", "排版2"))
        self.title_label.setText(_translate("MainWindow", "YoudaoRe"))
        self.input_select.setText(_translate("MainWindow", "..."))
        self.output_select.setText(_translate("MainWindow", "..."))
        self.link_txwh.setText(_translate("MainWindow", "踏雪无痕"))
        self.link_github.setText(_translate("MainWindow", "Github"))
import picture
